flyway.url=jdbc:postgresql://10.24.2.18:5432/GnanaThalam
flyway.user=postgres
flyway.password=NewStrongPassword

flyway.schemas=wf_integration
flyway.locations=filesystem:sql

flyway.baselineOnMigrate=true