flyway.url=${FLYWAY_URL}
flyway.user=${FLYWAY_USER}
flyway.password=${FLYWAY_PASSWORD}

flyway.schemas=public
flyway.locations=filesystem:/home/ccprj65/Gnanathalamschemaupdate/HR002/sql

flyway.baselineOnMigrate=true