name: Flyway Auto Deploy

on:
  push:
    branches:
      - Dev
      - UAT
      - Prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Branch Info
        run: |
          echo "================================="
          echo "AUTO DEPLOY START"
          echo "Branch: ${{ github.ref_name }}"
          echo "================================="

      - name: Make deploy script executable
        run: chmod +x deploy_all.sh

      - name: Run Flyway Deployment
        run: ./deploy_all.sh

      - name: Deployment Complete
        run: |
          echo "================================="
          echo "DEPLOYMENT SUCCESS"
          echo "================================="