name: Flyway Auto Deploy

on:
  push:
    branches:
      - Dev
      - UAT
      - Prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # =========================
      # STEP 1: Decide DB by branch
      # =========================
      - name: Set environment variables based on branch
        run: |
          echo "Branch = ${{ github.ref_name }}"

          if [ "${{ github.ref_name }}" = "Dev" ]; then
            echo "FLYWAY_URL=jdbc:postgresql://10.24.2.18:5432/GnanaThalam" >> $GITHUB_ENV

          elif [ "${{ github.ref_name }}" = "UAT" ]; then
            echo "FLYWAY_URL=jdbc:postgresql://10.24.2.18:5432/gnanathalam_14052026" >> $GITHUB_ENV

          elif [ "${{ github.ref_name }}" = "Prod" ]; then
            echo "FLYWAY_URL=jdbc:postgresql://10.24.2.18:5432/gnanathalam_18042026" >> $GITHUB_ENV
          fi

      # =========================
      # STEP 2: Secrets (always same)
      # =========================
      - name: Set DB credentials
        run: |
          echo "FLYWAY_USER=postgres" >> $GITHUB_ENV
          echo "FLYWAY_PASSWORD=NewStrongPassword" >> $GITHUB_ENV

      # =========================
      # STEP 3: Run deployment
      # =========================
      - name: Run Flyway Deploy
        run: |
          chmod +x deploy_all.sh
          ./deploy_all.sh